config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :replies
  resources :inquiries
  resources :buyers
  resources :houses
  resources :realtors
  resources :hunters
  # resources :users
  resources :companies
  resources :searches, only: [:new, :create, :show]
  resources :users
  devise_for :users,:path => 'us', :controllers => {:registrations => "registrations" ,omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users', to: 'users#new'
  # get '/us/sign_out', to: 'user/sessions#destroy'
  match '/users/new', to: 'users#new', via: 'get'
  match '/users', to: 'users#create', via: 'post'
  match '/interestList', to: 'buyers#showinterestlist', via: 'get' , as:'show_interest_list'
  match '/hunterIndex', to: 'hunter_index#index', via: 'get' , as:'hunter_index'
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: [:show, :edit, :update, :destroy]
  before_action :validateUser, only: [ :edit, :update, :destroy]
  # GET /houses
  # GET /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    @added = Hash.new
    @added["added"] = false
    @added["buyer"] = nil
    @inquiry = Inquiry.new
    @buyer = Buyer.new
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses
  # POST /houses.json
  def create
    @house = House.new(house_params)
    if @house.company_id == nil
      flash[:error] = "Please assign a company to your profile."
      render :new
      return
    end
    respond_to do |format|
      if @house.save
        format.html {redirect_to @house, notice: 'House was successfully created.'}
        format.json {render :show, status: :created, location: @house}
      else
        format.html {render :new}
        format.json {render json: @house.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /houses/1
  # PATCH/PUT /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html {redirect_to @house, notice: 'House was successfully updated.'}
        format.json {render :show, status: :ok, location: @house}
      else
        format.html {render :edit}
        format.json {render json: @house.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house.destroy
    respond_to do |format|
      format.html {redirect_to houses_url, notice: 'House was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_house
    @house = House.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def house_params
    params.require(:house).permit(:user_id, :company_id, :location, :size, :year, :style, :price, :floors, :basement, :owner, :contact , :image)
  end

  def validateUser
    if user_signed_in? && !(current_user.is_admin || current_user.id == @house.user_id)
      respond_to do |format|
        format.html {redirect_to home_index_path}
        return
      end
    end
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_form.html.erb
<%= form_with(model: house, local: true) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div style="display: none;">
      <%= form.text_field :user_id, value: current_user.id %>
    </div>
    <% if (current_user.is_realtor) && current_user.company_id != nil %>
      <div style="display: none;">
        <%= form.label :company_id, 'Company' %>
        <%= form.collection_select :company_id, Company.order(:c_name), :id, :c_name, {:selected => current_user.company_id} %>
      </div>
    <% end %>

    <% if current_user.is_admin %>
      <%= form.label :company_id, 'Select Company' %>
      <%= form.collection_select :company_id, Company.order(:c_name), :id, :c_name, prompt: true %>
    <% end %>


  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :size, 'Size (in sq.ft - whole numbers)' %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :year, 'Year (4-digit)' %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.select :style, options_for_select(['TownHouse', 'Single-Family Home', 'Condominium', 'Co-op', 'Multi-Family Home']), :include_blank => true %>
  </div>

  <div class="field">
    <%= form.label :price, 'Price (in dollars - whole numbers)' %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :floors, 'No. of floors (in numbers)' %>
    <%= form.number_field :floors %>
  </div>

  <div class="field">
    <%= form.label :basement %>
    <%= form.check_box :basement %>
  </div>

  <div class="field">
    <%= form.label :owner %>
    <%= form.text_field :owner %>
  </div>

  <div class="field">
    <%= form.label :contact, 'Owner contact number(US) - without country code' %>
    <%= form.text_field :contact %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" , :class=>"active btn btn-primary"%>
  </div>
<% end %>

app/views/houses/edit.html.erb
<br>
<h3>Edit House Listing</h3>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house, :class=>"active btn btn-primary"  %> |
<%= link_to 'Back', houses_path, :class=>"active btn btn-dark"  %>

app/views/houses/index.html.erb
<h3>House Listings</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Company Name</th>
    <th>Location</th>
    <th>Size</th>
    <th>Year</th>
    <th>Style</th>
    <th>Price</th>
    <th>Floors</th>
    <th>Basement</th>
    <th>Owner</th>
    <th>Contact</th>
    <th>Listed By</th>

  </tr>
  </thead>

  <tbody>
  <% @houses.each do |house| %>
    <tr>
      <td><%= house.company.c_name %></td>
      <td><%= house.location %></td>
      <td><%= house.size %></td>
      <td><%= house.year %></td>
      <td><%= house.style %></td>
      <td><%= house.price %></td>
      <td><%= house.floors %></td>
      <td><%= house.basement %></td>
      <td><%= house.owner %></td>
      <td><%= house.contact %></td>
      <td><%= house.user.fname %></td>
      <% if current_user.is_admin || (current_user.is_hunter && session[:as_hunter]) || (house.user_id == current_user.id && current_user.is_realtor && session[:as_realtor]) %>
        <td><%= link_to 'Show', house, :class=>"active btn btn-success"  %></td>
      <% end %>
      <% if (house.user_id == current_user.id && current_user.is_realtor && session[:as_realtor]) or current_user.is_admin %>
        <td><%= link_to 'Edit', edit_house_path(house), :class=>"active btn btn-primary"  %></td>
        <td><%= button_to "delete", house, :method => "delete" , :class=>"active btn btn-danger"%></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if current_user.is_admin || current_user.is_realtor %>
  <%= link_to 'New House', new_house_path, :class=>"active btn btn-dark"  %> |
<% end %>

<% if session[:dual_role] %>
  <% if session[:as_realtor] %>
    <%= link_to 'Back', home_index_path, :class=>"active btn btn-dark"  %>
  <% else %>
    <%= link_to 'Back', hunter_index_path , :class=>"active btn btn-dark" %>
  <% end %>
<% else %>
  <%= link_to 'Back', home_index_path, :class=>"active btn btn-dark"  %>
<% end %>

app/views/houses/new.html.erb
<% flash.each do |key, value| %>
  <p class="alert alert-danger"><%= value %></p>
<% end %>
<div style="margin-left: 1%">
<h3>List a house to be sold</h3>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path , :class=>"active btn btn-dark" %>
</div>

app/views/houses/show.html.erb
<br>
<h3>House Details</h3>
<div>
  <%= image_tag(@house.image.normal.url) if @house.image? %>
  <%= form_for @buyer  do |f| %>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Company Name</th>
        <th>Location</th>
        <th>Size</th>
        <th>Year</th>
        <th>Style</th>
        <th>Price</th>
        <th>Floors</th>
        <th>Basement</th>
        <th>Owner</th>
        <th>Contact</th>
        <th>Listed By</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td><%= @house.company.c_name %></td>
        <td><%= @house.location %></td>
        <td><%= @house.size %></td>
        <td><%= @house.year %></td>
        <td><%= @house.style %></td>
        <td><%= @house.price %></td>
        <td><%= @house.floors %></td>
        <td><%= @house.basement %></td>
        <td><%= @house.owner %></td>
        <td><%= @house.contact %></td>
        <td><%= @house.user.fname %></td>
        <% if current_user.is_hunter %>
          <% @house.buyers.each do |buyer|  %>
            <%if buyer.user_id == current_user.id %>
              <%  @added["added"] = true %>
              <%  @added["buyer"] = buyer %>
            <% else %>
              <% @added["added"] = false %>
            <% end %>
          <% end %>
          <div style="display: none;">
            <%= f.text_field :house_id, value: @house.id %>
          </div>
          <div style="display: none;">
            <%= f.text_field :user_id, value: current_user.id %>
          </div>
          <% if !@added["added"]%>
            <td><%= f.submit "Add to Interest List" %></td>
          <% else %>
            <td><div style="display: none;"><%= button_to 'Remove From Interest List',@added["buyer"], method: :delete, data: {confirm: 'Are you sure?'} %></div> <%= button_to "Remove From Interest List", @added["buyer"], :method => "delete" %></td>
          <% end %>
        <% end %>

  <% end %>
  </tr>
  </tbody>
  </table>
</div>
<% if current_user.is_realtor && (current_user.company_id == @house.company_id) %>
  <%= form_for @house do |f| %>
    <div>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <%= f.submit "Upload House Image" %>
  <% end %>
<% end %>
<br>
<%= link_to 'Back ', houses_path , :class=>"active btn btn-dark" %>
<% if current_user.is_hunter && session[:as_hunter] %>
  <%= link_to 'Submit/View My Queries', new_inquiry_path(:id => @house.id), :class=>"active btn btn-primary"  %>
<% end %>
<% if current_user.is_admin || ( current_user.is_realtor && (current_user.company_id == @house.company_id) && session[:as_realtor]) %>
  <%= link_to 'View Queries', new_inquiry_path(:id => @house.id), :class=>"active btn btn-primary"  %>
<% end %>
<% if current_user.is_realtor && (current_user.company_id == @house.company_id) && session[:as_realtor] %>
  <%= link_to 'View Potential Buyers', buyers_path(:id => @house.id), :class=>"active btn btn-primary"  %>
<% end %>