config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :replies
  resources :inquiries
  resources :buyers
  resources :houses
  resources :realtors
  resources :hunters
  # resources :users
  resources :companies
  resources :searches, only: [:new, :create, :show]
  resources :users
  devise_for :users,:path => 'us', :controllers => {:registrations => "registrations" ,omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users', to: 'users#new'
  # get '/us/sign_out', to: 'user/sessions#destroy'
  match '/users/new', to: 'users#new', via: 'get'
  match '/users', to: 'users#create', via: 'post'
  match '/interestList', to: 'buyers#showinterestlist', via: 'get' , as:'show_interest_list'
  match '/hunterIndex', to: 'hunter_index#index', via: 'get' , as:'hunter_index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.is_realtor && current_user.is_hunter
      session[:dual_role] = true
      session[:as_hunter] = false
      session[:as_realtor] = true
      current_user.is_hunter = false
    elsif current_user.is_realtor && !current_user.is_hunter
      session[:dual_role] = false
      session[:as_hunter] = false
      session[:as_realtor] = true
    elsif !current_user.is_realtor && current_user.is_hunter
      session[:dual_role] = false
      session[:as_hunter] = true
      session[:as_realtor] = false
    else
      session[:dual_role] = false
      session[:as_hunter] = false
      session[:as_realtor] = false
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if session[:dual_role] %>
  <a class="active btn btn-dark" style="text-align:center" href="<%= hunter_index_path %>">
    </svg>View as Hunter
  </a>
<% end %>
<table class="table">
  <tbody>
  <tr>
    <td>
      <div class="row" style={position:absolute}>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class=" nav-link active" href="<%= companies_path %>">
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                <polyline points="9 22 9 12 15 12 15 22"></polyline>
              </svg>
              List All Companies
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="<%= houses_path %>">
              <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                <polyline points="9 22 9 12 15 12 15 22"></polyline>
              </svg>
              List All Houses
            </a>
          </li>
          <% if current_user.is_hunter && !session[:dual_role] %>
            <li class="nav-item">
              <a class="nav-link active" href="<%= show_interest_list_path %>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                  <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                Interest List
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="<%= new_search_url %>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                  <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                Search for a house
              </a>
            </li>
          <% end %>
          <% if current_user.is_admin %>
            <li class="nav-item">
              <a class="nav-link active" href="<%= users_path %>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                  <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                List All Users
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="<%= new_user_path %>">
                <svg xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                  <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                Create New User
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="<%= new_company_path %>">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                  <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                Add New Companies
              </a>
            </li>
          <% end %>
        </ul>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;">
            <div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
              <div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div>
            </div>
            <div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;">
              <div style="position:absolute;width:200%;height:200%;left:0; top:0"></div>
            </div>
          </div>
          <div class="embed-responsive embed-responsive-21by9">
            <iframe class="embed-responsive-item" src="https://www.google.com"></iframe>
          </div>
        </main>
      </div>
    </td>
    <td><%= image_tag("estate.jpg", alt: "sample image") %></td>
  </tr>
  </tbody>
</table>