config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :replies
  resources :inquiries
  resources :buyers
  resources :houses
  resources :realtors
  resources :hunters
  # resources :users
  resources :companies
  resources :searches, only: [:new, :create, :show]
  resources :users
  devise_for :users,:path => 'us', :controllers => {:registrations => "registrations" ,omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users', to: 'users#new'
  # get '/us/sign_out', to: 'user/sessions#destroy'
  match '/users/new', to: 'users#new', via: 'get'
  match '/users', to: 'users#create', via: 'post'
  match '/interestList', to: 'buyers#showinterestlist', via: 'get' , as:'show_interest_list'
  match '/hunterIndex', to: 'hunter_index#index', via: 'get' , as:'hunter_index'
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :houses ,dependent: :destroy
  has_many :User , dependent: :destroy
  validates_presence_of :c_name, :website,:address
  validates_length_of :year, is: 4,  message: "Year must be in YYYY"
  validates :website, url: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:edit, :update, :destroy]
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end
  # GET /companies/1
  # GET /companies/1.json
  def show
  end
  # GET /companies/new
  def new
    @company = Company.new
  end
  # GET /companies/1/edit
  def edit
  end
  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        if current_user.is_realtor
          format.html { redirect_to edit_user_registration_path , notice: 'Company was successfully created.' }
         format.json { render :show, status: :created, location: @user }
        else
          format.html { redirect_to @company, notice: 'Company was successfully created.' }
          format.json { render :show, status: :created, location: @company }
        end
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:c_name, :website, :address, :size, :year, :revenue, :synopsis)
    end
    def validate_user
      if user_signed_in? && !(current_user.is_admin || current_user.company_id == @company.id)
        respond_to do |format|
          format.html {redirect_to home_index_path}
        end
      end
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6 mb-3">
    <%= form.label :c_name , 'Company Name' %>
    <%= form.text_field(:c_name ,{:class=>'form-control'} )%>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :website , 'Company Website'%>
    <%= form.text_field :website,{:class=>'form-control'} %>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :address ,'Location of Head Quarters'%>
    <%= form.text_field :address ,{:class=>'form-control'}%>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :size ,'Numeber of Realtors'%>
    <%= form.number_field :size,{:class=>'form-control'} %>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :year ,'Established in year(YYYY)'%>
    <%= form.number_field :year ,{:class=>'form-control'}%>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :revenue ,'Revenue(in millions)'%>
    <%= form.number_field :revenue,{:class=>'form-control'} %>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.label :synopsis,'Synopsis'%>
    <%= form.text_area :synopsis,{:class=>'form-control'} %>
  </div>

  <div class="col-md-6 mb-3">
    <%= form.submit "Submit", :class=>"active btn btn-primary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h3>Editing Company</h3>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company , :class=>"active btn btn-primary" %> |
<%= link_to 'Back', companies_path , :class=>"active btn btn-dark" %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Companies</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Company Name</th>
    <th>Website</th>
    <th>Address</th>
    <th>Size</th>
    <th>Year</th>
    <th>Revenue</th>
    <th>Synopsis</th>
  </tr>
  </thead>

  <tbody>
  <% @companies.each do |company| %>
    <tr>
      <td><%= company.c_name %></td>
      <td><%= company.website %></td>
      <td><%= company.address %></td>
      <td><%= company.size %></td>
      <td><%= company.year %></td>
      <td><%= company.revenue %></td>
      <td><%= company.synopsis %></td>
      <td><%= link_to 'Show', company, :class=>"active btn btn-success"  %></td>
      <% if current_user.is_admin || current_user.company_id == company.id %>
        <td><%= link_to 'Edit', edit_company_path(company), :class=>"active btn btn-primary"  %></td>
        <td><%= button_to "delete", company, :method => "delete", :class=>"active btn btn-danger" %></td>
      <% end %>

    </tr>
  <% end %>
  </tbody>
</table>

<br>
<% if current_user.is_admin %>
  <%= link_to 'New Company', new_company_path, :class=>"active btn btn-dark"  %> |
<% end %>

<% if session[:dual_role] %>
  <% if session[:as_realtor] %>
    <%= link_to 'Back', home_index_path, :class=>"active btn btn-dark"  %>
  <% else %>
    <%= link_to 'Back', hunter_index_path, :class=>"active btn btn-dark"  %>
  <% end %>
<% else %>
  <%= link_to 'Back', home_index_path, :class=>"active    btn btn-dark"  %>
<% end %>

app/views/companies/new.html.erb
<div class="col-md-6 mb-3">
<h3 class = "col-md-6 mb-3">Add a Company</h3>

<%= render 'form', company: @company %>

<%= link_to 'Back', :back, :class=>"active btn btn-dark"  %>
</div>

app/views/companies/show.html.erb
<h3>Company Details:</h3>
<br>
<table class="table table-striped" border="2">
  <tr>
    <th> Company Name</th>
    <th> Website</th>
    <th> Address</th>
    <th> Size</th>
    <th> Year</th>
    <th> Revenuer</th>
    <th> Synopsis</th>
  </tr>
  <tr>
    <td><%= @company.c_name %></td>
    <td><%= @company.website %></td>
    <td><%= @company.address %></td>
    <td><%= @company.size %></td>
    <td><%= @company.year %></td>
    <td><%= @company.revenue %></td>
    <td><%= @company.synopsis %></td>
  </tr>
</table>
<% if current_user.is_admin || current_user.company_id == @company.id%>
  <%= link_to 'Edit', edit_company_path(@company), :class=>"active btn btn-primary"  %> |
<% end %>
<%= link_to 'Back', companies_path, :class=>"active btn btn-dark"  %>