config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  resources :replies
  resources :inquiries
  resources :buyers
  resources :houses
  resources :realtors
  resources :hunters
  # resources :users
  resources :companies
  resources :searches, only: [:new, :create, :show]
  resources :users
  devise_for :users,:path => 'us', :controllers => {:registrations => "registrations" ,omniauth_callbacks: 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/users', to: 'users#new'
  # get '/us/sign_out', to: 'user/sessions#destroy'
  match '/users/new', to: 'users#new', via: 'get'
  match '/users', to: 'users#create', via: 'post'
  match '/interestList', to: 'buyers#showinterestlist', via: 'get' , as:'show_interest_list'
  match '/hunterIndex', to: 'hunter_index#index', via: 'get' , as:'hunter_index'
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  belongs_to :user
  belongs_to :house
  has_many  :replies , dependent: :destroy
  validates_presence_of :subject,:content
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
    @reply = Reply.new
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
    @inquiry.house_id = params[:id]
    # @inquiries = Inquiry.where(["user_id = ?", current_user.id])
    # @inquiries = @inquiries.where(["house_id = ?", params[:id]])
    @inquiries = Inquiry.where(["house_id = ?", params[:id]])
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)
    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to house_path(@inquiry.house), notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to house_path(@inquiry.house), notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @house = @inquiry.house
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to house_path(@house), notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:user_id, :house_id, :subject,:content)
    end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/inquiries/_form.html.erb
<%= form_for @inquiry do |form| %>
  <% if inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>
      <ul>
      <% inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div style="display: none;">
      <%= form.text_field :user_id, value: current_user.id %>
    </div>
    <div style="display: none;">
      <%= form.text_field :house_id, value:   @inquiry.house_id %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject %>
    </div>
    <div class="field">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="actions">
      <%= form.submit%>
    </div>
<% end %>

app/views/inquiries/edit.html.erb
<h3>Edit Inquiry</h3>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Back', house_path(@inquiry.house) %>

app/views/inquiries/index.html.erb
<h3>List of Inquiries</h3>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Subject</th>
    <th>Query</th>
  </tr>
  </thead>

  <tbody>
  <% @inquiries.each do |inquiries| %>
    <tr>
      <td><%= inquiries.subject %></td>

      <td><%= inquiries.content%></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', home_index_path %>

app/views/inquiries/new.html.erb
<% if current_user.is_hunter %>
  <h3>Submit a query</h3>
  <%= render 'form', inquiry: @inquiry %>
<% end %>

<br>
<br>

<h3>Inqueries</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Subject</th>
    <th>Query</th>
    <th>Created By</th>
  </tr>
  </thead>
  <tbody>
  <% @inquiries.each do |inquiry| %>
    <tr>
      <td><%= inquiry.subject %></td>
      <td><%= inquiry.content %></td>
      <td><%= inquiry.user.fname %></td>
      <td><%= link_to 'Show', inquiry_path(inquiry) %></td>
      <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
      <td><%= button_to "Delete", inquiry, :method => "delete" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/inquiries/show.html.erb
<p>
  <strong>Subject:</strong>
  <%= @inquiry.subject %>
</p>

<p>
  <strong>Query:</strong>
  <%= @inquiry.content %>
</p>

<p>
  <strong>Created By:</strong>
  <%= @inquiry.user.fname %>
</p>

<br>
<br>
<h3>All replies to this inquiry:</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Reply From</th>
    <th>Response</th>
  </tr>
  </thead>
  <tbody>
  <% @inquiry.replies.each do |reply| %>
    <tr>
      <td><%= reply.user.fname %></td>
      <td><%= reply.response %></td>
      <% if current_user.is_realtor && (current_user.company_id == reply.inquiry.house.company_id) %>
      <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
      <td><%= button_to "delete", reply, :method => "delete" %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<% if current_user.is_realtor && (current_user.company_id == @inquiry.house.company_id) %>
  <br>
  <br>
  <h3>Reply to user's inquiry:</h3>
  <br>
  <%= form_for @reply do |form| %>
    <div style="display: none;">
      <%= form.text_field :user_id, value: current_user.id %>
    </div>
    <div style="display: none;">
      <%= form.text_field :inquiry_id, value: @inquiry.id %>
    </div>
    <div class="field">
      <%= form.label :response ,"Reply to user's query:" %>
      <%= form.text_field :response %>
    </div>
    <div class="actions">
      <%= form.submit 'Send Reply' %>
    </div>
  <% end %>
<% end %>
<br>
<%= link_to 'Back', house_path(@inquiry.house) %>